### ISSUE TITLE
Just a thank you!

### ISSUE THREAD

**Issue by brendanheyu** [impauloalves/parcel-transformer-hbs#4]
Hi Paulo!

I currently am using Handlbars and Parcel 1 - I would love to use this plugin and move on to Parcel 2!

I currently inject the results of a template into a div in my index.html page - I use [navigo](https://github.com/krasimir/navigo) for simple routing - each route calls an endpoint for data, runs the data through the template and then injects the result into the afore mentioned div.

I would really appreciate hearing how you might do something similar - if you think I'm wildly off track! My current project cannot work with scope hoisting or any tree shaking for my js bundle - this is my ultimate goal. I know that this is due to my coding -not the projects in use. I'm self taught and very rough around the edges!

I appreciate if you don't have the time to respond - just know that I will be playing with your code to see how far I can go!

Obrigado!

**Comment by impauloalves** [comment]
Hi Brendan,
Were you able to solve the problem?
Best.

**Comment by brendanheyu** [comment]
Hi Paulo :)

Yes - and I love it! I now a very light setup, HB is working with Parcel2 nicely, routing implemented and all. 

Still looking for a peer that might look at what I'm up to and suggest better ways - but I'll get there.

Thank you for your efforts on this, really saved my bacon!

B
